version: '2'
services:
  simple-http-api:
    build: .
    expose:
      - "3000"
  nginx:
    image: nginx:latest
    links:
      - simple-http-api
    volumes:
      - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
      - "./static/:/static"
    ports:
      - "80:80"
