version: '2'
volumes:
  db-data:
  wordpress-data:
services:
  wordpress:
    image: wordpress
    volumes:
      - wordpress-data:/var/www/html/wp-content
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
