---
- hosts: all
  tasks:
    - name: install packages for this lab
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - nodejs
        - npm
    - name: install npm packages for this lab
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - forever
    - name: symlink /usr/bin/nodejs to /usr/bin/node
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link
    - name: create /app folder
      file:
        dest: /app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
    - name: install app to /app
      copy:
        src: files/app/
        dest: /app/
        owner: ubuntu
        group: ubuntu
    - name: install node_modules for app
      shell: "npm install && touch /tmp/app.installed"
      args:
        chdir: /app
        creates: /tmp/app.installed
      become: true
      become_user: ubuntu
    - name: start app
      shell: "forever start index.js && touch /tmp/app.started"
      args:
        chdir: /app
        creates: /tmp/app.started
      become: true
      become_user: ubuntu
    - name: remove default nginx index
      file:
        name: /var/www/html/index.nginx-debian.html
        state: absent
    - name: proxy_pass in nginx conf
      blockinfile:
        insertafter: '^.*server_name _'
        block: |
          location /api {
              proxy_pass http://127.0.0.1:3000/api;
          }
        path: /etc/nginx/sites-available/default
      notify: restart nginx
    - name: add our web files
      copy:
        src: "static/{{ item }}"
        dest: "/var/www/html/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - index.html
        - jquery.js
        - js.js
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
