---
- hosts: all
  tasks:
    - name: install server packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - bind9
    - name: create bind9 zones folder
      file:
        path: /etc/bind/zones
        owner: root
        group: root
        mode: 0755
        state: directory
    - name: install bind9 configuration files
      copy:
        src: "{{ item }}"
        dest: "/etc/bind/{{ item }}"
        owner: root
        group: root
        mode: 0644
      notify: restart bind9
      with_items:
        - named.conf.options
        - named.conf.local
        - zones/db.lab202.dyindude
  handlers:
    - name: restart bind9
      service:
        name: bind9
        state: restarted

