---
- hosts: all
  tasks:
    - name: install server packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - dnsmasq
    - name: allow port 53 tcp and udp in ufw
      ufw:
        rule: allow
        proto: any
        direction: in
        port: 53
