# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "server" do |server|
      server.vm.hostname = "dns-lab201-server"
      server.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "server.yml"
          ansible.become = true
      end
  end
  config.vm.define "client" do |client|
      client.vm.hostname = "dns-lab201-client"
      client.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "client.yml"
          ansible.become = true
      end
  end
end
